name: github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    
    - name: Install and Build
      run: yarn install && npm run build:prod

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      env:
        github_token: ${{ secrets.ACCESS_TOKEN }} 
        BRANCH: gh-pages
        FOLDER: dist
